networks:
  msg-network:

volumes:
  msg-mongo-data:

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: msg-mongodb
    networks:
      - msg-network
    volumes:
      - msg-mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:27017
  user-service:
    container_name: msg-user-service
    build:
      context: ./backend/user-service
    networks:
      - msg-network
    environment:
      STORAGE_PATH: ${STORAGE_PATH}
      APP_SECRET: ${APP_SECRET}
  chat-service:
    container_name: msg-chat-service
    build:
      context: ./backend/chat-service
    networks:
      - msg-network
    environment:
      STORAGE_PATH: ${STORAGE_PATH}
      APP_SECRET: ${APP_SECRET}
  envoy:
    container_name: msg-envoy
    build:
      context: ./envoy
    networks:
      - msg-network
    ports:
      - ${ENVOY_PORT}:808
  frontend:
    container_name: msg-frontend
    build:
      context: ./frontend
    ports:
      - ${FRONTEND_PORT}:4173
    environment:
      VITE_BASE_URL: ${VITE_BASE_URL}