networks:
  dev:

services:
  envoy:
    container_name: envoy
    build:
      context: ./envoy
    networks:
      - dev
    ports:
      - 810:810
  msgauth:
    container_name: msgauth
    build:
      context: ./backend/msgauth
    networks:
      - dev