config:
    env: "local"
    token_ttl: 1h
    
    app:
        max_message_length: 4000
    grpc:
        port: 810
        timeout: 10h #5s для prod
    storage:
        storage_name: "user-service"
        chats_collection: "chats"
        channels_collection: "channels"
        messages_collection: "messages"