version: "3"
tasks:
  genprotos:
    cmds:
      - task genuser
      
  genuser:
    cmds:
      - mkdir -p ../backend/v1/user-service/gen && protoc -I proto proto/v1/user-service.proto --go_out=../backend/v1/user-service/gen --go_opt=paths=source_relative --go-grpc_out=../backend/v1/user-service/gen --go-grpc_opt=paths=source_relative