version: "3"
tasks:
  genprotos:
    cmds:
      - task genauth && task genchat
  genuser:
    cmds:
      - mkdir -p ../backend/user-service/gen && protoc -I proto proto/user.proto --go_out=../backend/user-service/gen --go_opt=paths=source_relative --go-grpc_out=../backend/user-service/gen --go-grpc_opt=paths=source_relative
  genchat:
    cmds:
      - mkdir -p ../backend/msgchat/gen && protoc -I proto proto/msgchat.proto --go_out=../backend/msgchat/gen --go_opt=paths=source_relative --go-grpc_out=../backend/msgchat/gen --go-grpc_opt=paths=source_relative