  version: "3"
  tasks:
    run:
      aliases:
        - runflag
      desc: "Runs main.go file with correct config path in flag"
      cmds:
        - go run cmd/main.go -config="./config/local.yaml"
    proto:
      desc: "Generates pb files for Auth"
      cmds:
        - protoc -I ../../protos --go_out=./gen --go_opt=paths=source_relative --go-grpc_out=./gen --go-grpc_opt=paths=source_relative  ../../protos/msgchat.proto
